In [1]:
l = [23245, 27,546, 215, -1234]

In [2]:
l

[23245, 27, 546, 215, -1234]

In [3]:
## numpy arrays are better than default ones.
import numpy as np

In [5]:
a=np.array(l)

In [6]:
a

array([23245,    27,   546,   215, -1234])

In [7]:
#array cannot have different datatypes
b = np.array([12, "a", True, 'abc', 0.34]) 

In [8]:
b

array(['12', 'a', 'True', 'abc', '0.34'], 
      dtype='<U11')

In [9]:
print(b) #all elements became strings

['12' 'a' 'True' 'abc' '0.34']


In [10]:
a.mean

<function ndarray.mean>

In [11]:
a.mean()

4559.8000000000002

In [12]:
#matrix is two dimensional array

In [13]:
c=np.array([12, True])

In [14]:
print(c)

[12  1]


-------------

## Slicing arrays

In [15]:
l[0:2]

[23245, 27]

In [16]:
a

array([23245,    27,   546,   215, -1234])

In [17]:
a[2:]

array([  546,   215, -1234])

In [18]:
#important: when you slice an array you don 't create a copy!
b = a[2:4]

In [19]:
b

array([546, 215])

In [20]:
b[:] = 111

In [21]:
b

array([111, 111])

In [23]:
a #now has changed!!! b was a view of a, so now the values of a are 111

array([23245,    27,   111,   111, -1234])

In [24]:
#copy from a if you don 't want to change a
c= a.copy()

In [26]:
c[1] = 0

In [27]:
c

array([23245,     0,   111,   111, -1234])

In [28]:
a

array([23245,    27,   111,   111, -1234])

this is done to protect the computer's memory